version: '3.8'

services:
  api:
    build: .
    container_name: egg-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - DEBUG=${DEBUG}
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - egg-network

  db:
    image: postgres:15
    container_name: egg-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5445:5432"
    restart: unless-stopped
    networks:
      - egg-network

networks:
  egg-network:
    name: egg-netw

volumes:
  postgres_data:
