server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # SPA fallback (React Router) — pola TailAdmin/Vite
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Cache aset hash Vite
  location /assets/ {
    expires 30d;
    add_header Cache-Control "public, immutable";
  }

  gzip on;
  gzip_types text/css application/javascript application/json image/svg+xml;
}
